name: Wf-1
on: 
- push
- workflow_dispatch  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run: |
        echo "Welcome to Github Actions"
        hostnamectl 
        pwd
        echo $USER
        echo "******Bye****"
    - name: step2 (Check Python version)
      run: |
          python --version  
  job2:
    runs-on: windows-latest
    steps:
    - name: Window Cmds
      run: |
        dir 
        echo "Testing Windows"
  