name: Wf-11
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-slim
    steps:
    - name: Genrate Image Name
      id: Image_Gen
      run: |
         echo "image_name=docker.io/svreddy/myapp:v1" > "$GITHUB_OUTPUT"
         echo "Container_reg=hun.docker.com" >> "$GITHUB_OUTPUT"
    - name: Genrate Image Name 
      run: |
          echo "Image Name is ${{ steps.Image_Gen.outputs.image_name }}"
          echo "Reg URL is ${{ steps.Image_Gen.outputs.Container_reg }}"