name: WF-12
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-latest,ubuntu-slim]
         xyz: ["3.7","3.10"]
    steps: 
    - name: Step1
      run: |
          pwd
          cat /etc/passwd
          cat /etc/os*rel*
         