name: Code Checkout
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v7  
    - name: Install python
      uses: actions/setup-python@v7 
      with:
        python-version: 'python3.10'
    - name: Run the Code
      run : |
        python 1.py
    

