name: Code Checkout
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v7  
    - name: Install python
      run: |
        sudo apt update
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install python3.10 python3.10-venv python3.10-dev -y
    - name: Run the Code
      run : |
        python 1.py
    

