name: Image Build
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7 
    - name: setup docker
      uses: docker/setup-buildx-action@v4
    - name: Build Image
      uses: docker/build-push-action@v7
      with:
        tags: myimage:latest
    - name: Diaplay Images
      run: |
        docker image ls      
