name: Image Build
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7 
    - name: setup docker
      uses: docker/setup-buildx-action@v4
    - name: Doker Reg Login 
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERREG_USER }}
        password: ${{ secrets.DOCKER_REG_PASSWD }}      
    - name: Build Image
      uses: docker/build-push-action@v7
      with:
        context: .
        tags: docker.io/svreddy0111/myximage:latest
        load: true
        push: true
    - name: Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.xserverip }}
        username: ${{ vars.xserveruser }}
        key: ${{ secrets.XSERVERKEY }}
        script: |
          docker run -d docker.io/svreddy0111/myximage:latest
          docker ps -a
          
  
  