name: wf-2
on: push
jobs:
  jobx:
    runs-on: ubuntu-slim
    steps: 
    - name: check current user
      run: |
        pwd
        whoami
    - name: check docker version
      run: |
         docker --version      