name: Wf-3
on: workflow_dispatch
env:
  APP_NAME: 'IOSAPP'
  IMAGE_NAME: 'docker.io/sheshi/image:latest'
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'WindowsApp'
      Owner: 'Hsbc Corp'
    steps:
    - name: Step1
      env:
        APP_NAME: 'LinuxApp'
        Rel_Name: 'Aug26'
      run: | 
         echo "App name is ${{ env.APP_NAME }}"
         echo "Owner Name is ${{ env.Owner }} "
         echo "Image Name is ${{ env.IMAGE_NAME }}" 
         echo "Rel Name is ${{ env.Rel_Name }}" 
    - name: Step2 
      run: |
         echo "App name is ${{ env.APP_NAME }}"
         echo "Owner Name is ${{ env.Owner }} "
         echo "Image Name is ${{ env.IMAGE_NAME }}"
         echo "Rel Name is ${{ env.Rel_Name }}" 
                 
  job2:
    runs-on: ubuntu-slim
    steps:
    - name: Pring WF Env Vars
      run: |
         echo "App name is ${{ env.APP_NAME }}"
         echo "Image Name is ${{ env.IMAGE_NAME }}" 
         echo "Owner Name is ${{ env.Owner }} "
               