name: Wf-4
on: workflow_diaptach
jobs:
  jobx:
    runs-on: ubuntu-slim
    steps:
    - name: step1
      run: |
        echo "APPROVER_NAME is ${{ vars.APPROVER_NAME }}"
        echo "Clinet App Ver is ${{ vars.CLIENT_APP_VER }}"