name: Wf-4
on: workflow_dispatch
jobs:
  jobx:
    runs-on: ubuntu-slim
    steps:
    - name: step1
      run: |
        echo "APPROVER_NAME is ${{ vars.APPROVER_NAME }}"
        echo "Clinet App Ver is ${{ vars.CLIENT_APP_VER }}"
        echo "DOCKER_REG Passwd is ${{ secrets.DOCKER_REG }}"
        sleep 30
  joby:
    runs-on: ubuntu-latest
    steps:
    - name: stepx
      run:
         echo "Hell This is Job2"       